name: Build and Deploy Back-end on AWS
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create back-end env file
        uses: SpicyPizza/create-envfile@v1.3.1
        with:
          envkey_POSTGRES_USERNAME: ${{secrets.POSTGRES_USERNAME}}
          envkey_POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          envkey_POSTGRES_HOST: ${{secrets.POSTGRES_HOST}}
          envkey_POSTGRES_PORT: ${{secrets.POSTGRES_PORT}}
          envkey_POSTGRES_DATABASE: ${{secrets.POSTGRES_DATABASE}}
          envkey_DATABASE_URL: ${{secrets.DATABASE_URL}}
          envkey_REDIS_URL: ${{secrets.REDIS_URL}}
          envkey_SECRET_JWT: ${{secrets.SECRET_JWT}}
          envkey_IGDB_API_KEY: ${{secrets.IGDB_API_KEY}}
          envkey_IGDB_CLIENT_ID: ${{secrets.IGDB_CLIENT_ID}}
          file_name: .env
          fail_on_empty: true
      - name: Build
        run: docker compose build
      - name: Run
        run: docker compose stop && docker compose up -d
